 source ‘git@gitee.com:zbFish/ZBFMSpecs.git’
 source ‘https://github.com/CocoaPods/Specs.git’

 platform :ios, ‘8.0’

target 'ZBFM' do
  use_frameworks!
#  pod 'ZBFMBase/Categoty'
#  pod 'ZBFMBase', :subspecs => ['Base', 'Categoty']
   pod 'ZBFMMain'

end
